### ISSUE TITLE
Error when saving computer object

### ISSUE THREAD

**Issue by Ozaad** [bytemine/univention-openvpn#2]
Hi,

I installed OpenVPN4UCS on my DC Master, started trying out the OpenVPN and got distracted. After some time I wanted to give it a new try, but now editing my DC Master in the UMC results in the following error message:
The LDAP object could not be saved: LDAP Error Object class violation: attribute 'univentionOpenvpnSecret' not allowed

I never added the/a OpenVPN secret for a site-to-site connection but cannot now save the computer object. When uninstalling OpenVPN4UCS everything works fine as long as I don't reinstall the app on the same server and re-run the joinscripts. After re-running the joinscripts the same error occurs.

Any tips?

Regards,
Timo

PS: Proficient UCS administrator at Univention PS but running a private project.

**Comment by hra** [comment]
Probably the univention-openvpn schema extension, which contains this attribute definition, is missing.
Is the package 'univention-openvpn-schema' installed? What does 

udm computers/domaincontroller_master list

output? Does it contain any openvpn\* attributes?

**Comment by Ozaad** [comment]
Hello hra,

univention-openvpn-schema is installed:
ii  univention-openvpn-schema                                      1.1.9

and the udm command returns one object: the server the app is installed on and was previously configured at. It contains openvpn\* attributes.

**Comment by hra** [comment]
The command

univention-ldapsearch '(univentionObjectType=computers/domaincontroller_master)' \ univentionOpenvpnSitetoSite

should output a list containing all objectclasses and sitetosite related attributes on your master. Does it contain the line

objectClass: univentionOpenvpnSitetoSite

or any univention\* attribute?

**Comment by Ozaad** [comment]
Yes, the objectClass univentionOpenvpnSitetoSite is set, and so is a value for univentionOpenvpnSecret.

I never enabled a Site-to-Site configuration on my OpenVPN server. So how does this objectClass get into the DC Master LDAP object? And is there a more convenient way to get that attribute and objectClass rid of than using ldapmodify?

**Comment by hra** [comment]
The univentionOpenvpnSecret is set in the univention-openvpn-sitetosite join script. It exists whether sitetosite is active or not. The strange thing is - 'objectClass: univentionOpenvpnSitetoSite' allows univentionOpenvpnSecret as an attribute, so above error should not occur. The output of

univention-ldapsearch -b cn=Subschema -s base objectClasses

should contain the univentionOpenvpnSitetoSite definition. Can you please check if the attribute list really contains univentionOpenvpnSecret?

**Comment by Ozaad** [comment]
Seems to be present:
`timo@ucs-master:~$ sudo univention-ldapsearch -LLLo ldif-wrap=no -b cn=Subschema -s base objectClasses | grep -i univentionOpenvpnSecret

objectClasses: ( 1.3.6.1.4.1.10176.99998.7697.2.3 NAME 'univentionOpenvpnSitetoSite' DESC 'OpenVPN sitetosite config' SUP top AUXILIARY MAY ( univentionOpenvpnSitetoSitePort $ univentionOpenvpnRemote $ univentionOpenvpnLocalAddress $ univentionOpenvpnRemoteAddress $ univentionOpenvpnSecret $ univentionOpenvpnSitetoSiteActive $ univentionOpenvpnLicense ) )`

**Comment by Ozaad** [comment]
Any chance of fixing this? It's a real bummer I cannot edit the computer object any more and this is a total no-go...

**Comment by hra** [comment]
Since your slapd's live schema config and the UMC error message contradict each other, it seems the error message is wrong or at least misleading. So as a quick solution I'd suggest removing openvpn4ucs.
If you want to debug this further, turn on slapd logging (at least 0x100), reproduce the error and check the logfile to find out what actually fails.

**Comment by Ozaad** [comment]
As written in my initial comment:

> When uninstalling OpenVPN4UCS everything works fine as long as I don't reinstall the app on the same server and re-run the joinscripts. After re-running the joinscripts the same error occurs.

I will try your App update later (got the newsletter today) and check if fixes the issue....

**Comment by Ozaad** [comment]
After updating to version 1.1.10 the error stays the same.

Any chance to get this fixed without
- uninstalling the app,
- checking the unjoinscript for missed steps,
- modifying my LDAP manually, and
- reinstalling the app, hoping the error is not coming back?

**Comment by Ozaad** [comment]
I sorted it out the really hard and nasty way:
- Uninstalling the app using the App Center
- Made sure nothing is left from the App on the file system
- Created `ldif` files for every single computer in the domain
- Used ldapmodify to purge everything from OpenVPN4UCS from the LDAP
- Reinstalled the app and started over.

Now everything works like a charm and we can finally evaluate the App and OpenVPN (well, end user connections. site-to-site is a new topic, but we will come back to this via the support/licence channel).

Somewhere in-between our initial installation of the App and the Update to 1.1.9, something went horribly wrong and caused this error! Nevertheless, got it working now...
