### ISSUE TITLE
Missing unjoin-script?

### ISSUE THREAD

**Issue by Ozaad** [bytemine/univention-openvpn#3]
Do you provide unjoin-scripts with your app (http://docs.software-univention.de/developer-reference-4.1.html#join:unjoin)? If so, are all attributes and object classes on an object in the LDAP deleted? Would there be much use leaving them behind when uninstalling (the last instance of) OpenVPN4UCS?

**Comment by hra** [comment]
Yes, we do (06*-uninstall.uinst). But those scripts should only remove any objects from LDAP which were created by the app itself, not attributes added to user defined data by the UMC. (According to Univention, the deinstallation of an app should not modify any user data.). It is therefore mandatory, that schema extensions are not deinstalled on app removal.

This also ensures that you do not loose any configuration data if you unistall and later reinstall an app.
