### ISSUE TITLE
UCS-4.2-3 errata 259 Client VPN Config generation is broken (ready2go) 

### ISSUE THREAD

**Issue by rotor-head** [bytemine/univention-openvpn#4]
Just updated the UCS master prior to installing OpenVPN4UCS for the first time. 

Per the PDF, once a user has VPN enabled, the appropriate certificates along with configurations are to be bundled and dropped into /downloads/{user}/ for collection by the user via the web gui.

Reviewing the path information, I looked into /var/www/downloads as well as /etc/openvpn and was expecting to see a zip archive and config files, respectively, available in these system paths.

It's my presumption that the scripts fire upon saving the change to the user in the UCS Management Console when enabling VPN. It appears the linkage for the save action to initiate the OpenVPN scripts is missing.

**Comment by hra** [comment]
UCS 4.2 displays default values for existing objects without actually setting them. Please set the fields `server address, port, transfer network IPv4` to 0 (yes, single digit) and save.

Reopen the OpenVPN4UCS settings, change the 0s to correct values for address, port and network, save.
