### ISSUE TITLE
App does not work since UCS 4.3

### ISSUE THREAD

**Issue by it25fg** [bytemine/univention-openvpn#5]
Recently tried to install openvpn4ucs on UCS 4.4 and saw join scripts failing. The offending statement was
```
udm users/user remove "$@" \
        --dn "uid=$name,cn=users,$ldap_base" > /dev/null 2>&1
univention-directory-manager users/user create "$@" \
        --position "cn=users,$ldap_base" \
        --option "ldap_pwd" \
        --set username=$name \
        --set lastname=$name \
        --set password=$pw

```
Since UCS 4.3, there's no 'ldap_pwd' option for an ordinary user; instead they have created a different object type for this:
```
root@remote:/usr/lib/univention-install# udm modules | grep users
  users/contact
  users/ldap
  users/passwd
  users/self
  users/user
```
In this case, 'users/ldap' should be used.

Is this the right place to get the app working again?

Thanks,
Frank.

**Comment by dra** [comment]
Hi Frank. Thanks for reporting! We currently investigate this in different scenarios and get back to you once we could reproduce and figure out the exact issue.

**Comment by dra** [comment]
Hi. We were able to reproduce and fix this behaviour; a new version has been built and is currently tested before it is published in the app center.

**Comment by hra** [comment]
Hello,

as of today, the new version is still being tested by Univention. It will (amongst others) revert to the old behaviour of creating its technical users as simple accounts, thus not counting towards the UCS license.

If you do not want to wait for the official publication, you can already get the new version (1.1.17)  from the test-appcenter.
